### ISSUE TITLE
How to compile code?

### ISSUE THREAD

**Issue by bobybobybob** [AlexPutz/stm32dntp#2]
Windows 7 - 64 
Arduino IDE 1.8.5
Stm32 Board Software    https://github.com/rogerclarkmelbourne/Arduino_STM32

What do you use for Compile? I cant compile it.

...

C:\Users\Q\Documents\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/include/libmaple/systick.h:83: multiple definition of `rtclock'

C:\Users\Q\AppData\Local\Temp\arduino_build_837423\sketch\sntp_utils.cpp.o:C:\Users\Q\Documents\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/include/libmaple/systick.h:83: first defined here

collect2.exe: error: ld returned 1 exit status

Using library Serasidis_EtherCard_STM at version 1.0 in folder: C:\Users\Q\Documents\Arduino\hardware\Arduino_STM32-master\STM32F1\libraries\Serasidis_EtherCard_STM 
Using library EEPROM in folder: C:\Users\Q\Documents\Arduino\hardware\Arduino_STM32-master\STM32F1\libraries\EEPROM (legacy)
Using library stm32dntp-master in folder: C:\Users\Q\Documents\Arduino\libraries\stm32dntp-master (legacy)
Using library RTClock at version 1.0 in folder: C:\Users\Q\Documents\Arduino\hardware\Arduino_STM32-master\STM32F1\libraries\RTClock 
Using library SPI at version 1.0 in folder: C:\Users\Q\Documents\Arduino\hardware\Arduino_STM32-master\STM32F1\libraries\SPI 
exit status 1
Error compiling for board Generic STM32F103C series.`

**Comment by bobybobybob** [comment]
OK it work now. I have to install the ZIP as Libary and not extract all in a folder and open the ino in it. 

Great Job, it work :-) 

Do you will make a Version in future with little Display so a easy look on device you can see that all working perfect? Printing Time and other Status Stuff?

**Comment by AlexPuts** [comment]
I did had an led seven segment display displaying it back when i started, its a secondary function for a server, but it can be easily added by yourself. It was intended to stay in the places where you cant see it anyway.
